services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: cat-user-api
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  mongo_data:
